genome:
    "/home/Shared/data/seq/microexon_simulation/GRCh37.82/genome/Homo_sapiens.GRCh37.dna.primary_assembly.fa"

chromosomes:
    - 19
    - 22

simulation_name: simulated_reads_chr19_22

## gtf files with removed mes / exons
reduced_gtf:
    me: "simulation/reduced_GTF/GRCh37.85_chr19_22_reduced_me.gtf"
    exon: "simulation/reduced_GTF/GRCh37.85_chr19_22_reduced_exon.gtf"
    me_exon: "simulation/reduced_GTF/GRCh37.85_chr19_22_reduced_me_exon.gtf"

## gtf files of the removed mes / exons
reduced_exons:
    me: "simulation/reduced_GTF/removed_me.gtf"
    exon: "simulation/reduced_GTF/removed_exon.gtf"
    me_exon: "simulation/reduced_GTF/removed_me_exon.gtf"

## direcory with the removed and reduced gtf files
reduced_dir:
    "simulation/reduced_GTF"

star_param:
    default: ""
    outSJfilterOverhangMin9: "--outSJfilterOverhangMin 30 9 9 9"
    outSJfilterOverhangMin6: "--outSJfilterOverhangMin 30 6 6 6"
    outSJfilterCountTotalMin3: "--outSJfilterCountTotalMin 3 3 3 3"
    scoreGenomicLengthLog2scale0: "--scoreGenomicLengthLog2scale 0"
    alignSJoverhangMin3: "--alignSJoverhangMin 3"
    # outSJfilterDistToOtherSJmin0_outSJfilterOverhangMin6: "--outSJfilterDistToOtherSJmin 0 0 0 0 --outSJfilterOverhangMin 30 6 6 6"

tophat_param:
    default: ""
    microexons_search: "--microexon-search"


##directory with the EQP scripts
eqp: "/home/kathi/software/EQP-QM-master"

## directory with EQP setup files
eqp_setup: "reference/EQP_setup"
