genome:
    "/home/Shared/data/seq/microexon_simulation/GRCh37.82/genome/Homo_sapiens.GRCh37.dna.primary_assembly.fa"

chromosomes:
    - 19
    - 22

simulation_name: simulated_reads_chr19_22

## gtf files with removed mes / exons
reduced_gtf:
    me: "simulation/reduced_GTF/GRCh37.85_chr19_22_reduced_me.gtf"
    exon: "simulation/reduced_GTF/GRCh37.85_chr19_22_reduced_exon.gtf"
    me_exon: "simulation/reduced_GTF/GRCh37.85_chr19_22_reduced_me_exon.gtf"

## gtf files of the removed mes / exons
reduced_exons:
    me: "simulation/reduced_GTF/removed_me.gtf"
    exon: "simulation/reduced_GTF/removed_exon.gtf"
    me_exon: "simulation/reduced_GTF/removed_me_exon.gtf"

## direcory with the removed and reduced gtf files
reduced_dir:
    "simulation/reduced_GTF"

star_param:
    default: ""
    outSJfilterOverhangMin9: "--outSJfilterOverhangMin 30 9 9 9"
    outSJfilterOverhangMin6: "--outSJfilterOverhangMin 30 6 6 6"
    outSJfilterCountTotalMin3: "--outSJfilterCountTotalMin 3 3 3 3"
    scoreGenomicLengthLog2scale0: "--scoreGenomicLengthLog2scale 0"
    alignSJoverhangMin3: "--alignSJoverhangMin 3"
    # outSJfilterDistToOtherSJmin0_outSJfilterOverhangMin6: "--outSJfilterDistToOtherSJmin 0 0 0 0 --outSJfilterOverhangMin 30 6 6 6"

tophat_param:
    default: ""
    microexons_search: "--microexon-search"


##directory with the EQP scripts
eqp: "/home/kathi/software/EQP-QM-master"

## directory with EQP setup files
eqp_setup: "reference/EQP_setup"

## stringtie parameters
# -a <int>  Junctions that don't have spliced reads that align across them with at least this amount
            # of bases on both sides are filtered out. Default: 10
# -c <float>    Sets the minimum read coverage allowed for the predicted transcripts.
                # A transcript with a lower coverage than this value is not shown in the output. Default: 2.5
#  --> probably we will have to lower this value, most lowly expressed transcripts will not be recovert with 2.5
# -f <0.0-1.0>  Sets the minimum isoform abundance of the predicted transcripts as a fraction of the most abundant transcript
                # assembled at a given locus. Lower abundance transcripts are often artifacts of incompletely spliced precursors
                # of processed transcripts. Default: 0.1
# -j <float>    There should be at least this many spliced reads that align across a junction (i.e. junction coverage). This number
            # can be fractional, since some reads align in more than one place. A read that aligns in n places will contribute 1/n to
            # the junction coverage. Default: 1
# -t    This parameter disables trimming at the ends of the assembled transcripts. By default StringTie adjusts the predicted transcript's start
            # and/or stop coordinates based on sudden drops in coverage of the assembled transcript.
# default
# -a 3
# -a 6 (min value in STAR alignment)
# -c 1
# -f 0.05
# -f 0.2
# -j 1 (STAR value) --> no change required?
# -t (probably we should not set this parameter, but I still want to know what happens if we use it)
stringtie_param:
    default: ""
    minJuncOverhang6:    "-a 6"
    minJuncOverhang3:    "-a 3"
    minReadCoverage1:   "-c 1"
    minIsoformAbundance0.05:    "-f 0.05"
    minIsoformAbundance0.2:    "-f 0.2"
    noEndTrimming:  "-t"
    minReadCoverage1_minIsoformAbundance0.05:   "-c 1 -f 0.05"
