## All paths defined in this configuration file must be either absolute or relative to the 
## location of the Snakefile!


## human RNA-seq sample for simulation
##--------------------------------------------------------------------------------------------

## data was downloaded from ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByExp/sra/SRX/SRX160/SRX1603411/SRR3192428/
## GEO https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2072377
FASTQ1: "/home/Shared/data/seq/microexon_simulation/microexon_study/real_data/SRR3192428_1.fastq.gz"
FASTQ2: "/home/Shared/data/seq/microexon_simulation/microexon_study/real_data/SRR3192428_2.fastq.gz"
## directory in which the reference genome fasta sequences are stored:
## Homo_sapiens.GRCh37.dna.chromosome.19.fa
## Homo_sapiens.GRCh37.dna.chromosome.22.fa
GENOMEDIR: "/home/Shared/data/seq/microexon_simulation/microexon_study/genome/reference/"
## prefix of the RSEM reference files
RSEMREF: "reference/RSEM/hg19_chr19_22"
## name of the RNA-seq sample
REALSAMPLE: "/home/Shared/data/seq/microexon_simulation/microexon_study/real_data/"
## index of the RNA-seq sample
SAMPLENAME: "SRR3192428"
## theta paramter for rsem-simulate-reads
## This parameter determines the fraction of reads  that  are  coming  from  background  "noise"  (instead  of  from  a transcript)
THETA: 0.05
## How many reads should be simulated?
N_READS: 1118017
## the number of reads that were mapped to chromosome 19 and 22: 1118017
## 8306564 = number of reads = [348875684]/4*{1500+500}/(21000)        [lines in real fastq data] {genes in chr19 + chr22} / (total genes)

## seed for ransom numbere generator in rsem-simulate-reads
SEED: 584

## Number of cores
##--------------------------------------------------------------------------------------------
## maximal number of cores to use
cores: 12

## Gene annotation file
##--------------------------------------------------------------------------------------------
gtf : "annotation/Homo_sapiens.GRCh37.85_chr19_22.gtf"

## Mapping parameters
##--------------------------------------------------------------------------------------------

genome:
    "/home/Shared/data/seq/microexon_simulation/GRCh37.82/genome/Homo_sapiens.GRCh37.dna.primary_assembly.fa"

chromosomes:
    - 19
    - 22

simulation_name: simulated_reads_chr19_22

## gtf files with removed mes / exons
reduced_gtf:
    me: "simulation/reduced_GTF/GRCh37.85_chr19_22_reduced_me.gtf"
    exon: "simulation/reduced_GTF/GRCh37.85_chr19_22_reduced_exon.gtf"
    me_exon: "simulation/reduced_GTF/GRCh37.85_chr19_22_reduced_me_exon.gtf"

## gtf files of the removed mes / exons
reduced_exons:
    me: "simulation/reduced_GTF/removed_me.gtf"
    exon: "simulation/reduced_GTF/removed_exon.gtf"
    me_exon: "simulation/reduced_GTF/removed_me_exon.gtf"

## direcory with the removed and reduced gtf files
reduced_dir:
    "simulation/reduced_GTF"

star_param:
    default: ""
    outSJfilterOverhangMin9: "--outSJfilterOverhangMin 30 9 9 9"
    outSJfilterOverhangMin6: "--outSJfilterOverhangMin 30 6 6 6"
    outSJfilterCountTotalMin3: "--outSJfilterCountTotalMin 3 3 3 3"
    scoreGenomicLengthLog2scale0: "--scoreGenomicLengthLog2scale 0"
    alignSJoverhangMin3: "--alignSJoverhangMin 3"
    # outSJfilterDistToOtherSJmin0_outSJfilterOverhangMin6: "--outSJfilterDistToOtherSJmin 0 0 0 0 --outSJfilterOverhangMin 30 6 6 6"

## Star parameters for exon discovery
overhang_min:
    default: "12"
    outSJfilterOverhangMin9: "9"
    outSJfilterOverhangMin6: "6"
    outSJfilterCountTotalMin3: "12"
    scoreGenomicLengthLog2scale0: "12"
    alignSJoverhangMin3: "12"

tophat_param:
    default: ""
    microexons_search: "--microexon-search"

hisat2_dir: /home/kathi/software/hisat2-2.1.0/


##directory with the EQP scripts
eqp: "/home/kathi/software/EQP-QM-master"

## directory with EQP setup files
eqp_setup: "reference/EQP_setup"

## stringtie parameters
# -a <int>  Junctions that don't have spliced reads that align across them with at least this amount
            # of bases on both sides are filtered out. Default: 10
# -c <float>    Sets the minimum read coverage allowed for the predicted transcripts.
                # A transcript with a lower coverage than this value is not shown in the output. Default: 2.5
#  --> probably we will have to lower this value, most lowly expressed transcripts will not be recovert with 2.5
# -f <0.0-1.0>  Sets the minimum isoform abundance of the predicted transcripts as a fraction of the most abundant transcript
                # assembled at a given locus. Lower abundance transcripts are often artifacts of incompletely spliced precursors
                # of processed transcripts. Default: 0.1
# -j <float>    There should be at least this many spliced reads that align across a junction (i.e. junction coverage). This number
            # can be fractional, since some reads align in more than one place. A read that aligns in n places will contribute 1/n to
            # the junction coverage. Default: 1
# -t    This parameter disables trimming at the ends of the assembled transcripts. By default StringTie adjusts the predicted transcript's start
            # and/or stop coordinates based on sudden drops in coverage of the assembled transcript.
# default
# -a 3
# -a 6 (min value in STAR alignment)
# -c 1
# -f 0.05
# -f 0.2
# -j 1 (STAR value) --> no change required?
# -t (probably we should not set this parameter, but I still want to know what happens if we use it)
stringtie_param:
    default: ""
    minJuncOverhang6:    "-a 6"
    minJuncOverhang3:    "-a 3"
    minReadCoverage1:   "-c 1"
    minIsoformAbundance0.05:    "-f 0.05"
    minIsoformAbundance0.2:    "-f 0.2"
    noEndTrimming:  "-t"
    minReadCoverage1_minIsoformAbundance0.05:   "-c 1 -f 0.05"

## R setup
Rbin: "/usr/local/R/R-3.6.0/bin/R"
